<?php

namespace Database\Seeders;

use App\Models\WebContent;
use Illuminate\Database\Seeder;

class WebContentSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            [
                'section' => 'home',
                'key' => 'home_hero',
                'name' => 'Hero principal',
                'title' => 'Equipos y alimentos para tu negocio',
                'subtitle' => 'Importación segura con respaldo local',
                'body' => 'Actualiza este bloque desde el panel para controlar el mensaje principal de la web.',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'home',
                'key' => 'home_hero_secondary',
                'name' => 'Hero secundario',
                'title' => 'Soluciones de alta calidad con soporte especializado',
                'subtitle' => 'Reconocemos las necesidades de cada cliente y proponemos equipos con enfoque en productividad.',
                'body' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'about',
                'key' => 'about_story',
                'name' => 'Historia de la empresa',
                'title' => 'Nuestra trayectoria',
                'subtitle' => 'Más de 10 años impulsando negocios',
                'body' => 'Edita aquí la historia institucional, misión y propuesta de valor.',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'about',
                'key' => 'about_mission',
                'name' => 'Misión',
                'title' => 'Misión',
                'subtitle' => null,
                'body' => 'Reconocer necesidades de producción y responder con maquinaria confiable, soporte técnico y respaldo de proveedores internacionales.',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'about',
                'key' => 'about_vision',
                'name' => 'Visión',
                'title' => 'Visión',
                'subtitle' => null,
                'body' => 'Ser el mejor aliado estratégico de nuestros clientes con propuestas de valor que impulsen su rentabilidad.',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'banners',
                'key' => 'home_banner_top',
                'name' => 'Banner superior home',
                'title' => 'Promoción destacada del mes',
                'subtitle' => 'Carga imagen y texto promocional',
                'body' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'process',
                'key' => 'process_step_1',
                'name' => 'Paso 1 del proceso',
                'title' => 'Diagnóstico',
                'subtitle' => null,
                'body' => 'Entendemos tu capacidad, proceso y objetivo de producción.',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'process',
                'key' => 'process_step_2',
                'name' => 'Paso 2 del proceso',
                'title' => 'Propuesta técnica',
                'subtitle' => null,
                'body' => 'Seleccionamos equipos y materias primas según requerimiento real.',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'process',
                'key' => 'process_step_3',
                'name' => 'Paso 3 del proceso',
                'title' => 'Importación y entrega',
                'subtitle' => null,
                'body' => 'Coordinamos suministro con respaldo de proveedores internacionales.',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'process',
                'key' => 'process_step_4',
                'name' => 'Paso 4 del proceso',
                'title' => 'Puesta en marcha',
                'subtitle' => null,
                'body' => 'Acompañamos instalación, arranque y soporte operativo.',
                'sort_order' => 4,
                'is_active' => true,
            ],
            [
                'section' => 'stats',
                'key' => 'stat_1',
                'name' => 'Estadística 1',
                'title' => 'Año de fundación',
                'subtitle' => '2021',
                'body' => null,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'stats',
                'key' => 'stat_2',
                'name' => 'Estadística 2',
                'title' => 'Líneas de solución',
                'subtitle' => '4',
                'body' => null,
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'stats',
                'key' => 'stat_3',
                'name' => 'Estadística 3',
                'title' => 'Enfoque de soporte',
                'subtitle' => 'Técnico',
                'body' => null,
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'contact',
                'key' => 'contact_main',
                'name' => 'Bloque principal de contacto',
                'title' => 'Contáctanos',
                'subtitle' => 'Atención personalizada para tu empresa',
                'body' => 'Puedes editar teléfonos, correos y llamados a la acción desde este registro.',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'faq',
                'key' => 'faq_1',
                'name' => 'Pregunta frecuente 1',
                'title' => '¿Trabajan con equipos nuevos y usados?',
                'subtitle' => null,
                'body' => 'Sí. Ofrecemos opciones nuevas y usadas según el presupuesto y los objetivos del cliente.',
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'section' => 'faq',
                'key' => 'faq_2',
                'name' => 'Pregunta frecuente 2',
                'title' => '¿También suministran materias primas?',
                'subtitle' => null,
                'body' => 'Sí. Incluimos tripas de colágeno y aditivos no cárnicos como parte de la solución integral.',
                'sort_order' => 2,
                'is_active' => true,
            ],
            [
                'section' => 'faq',
                'key' => 'faq_3',
                'name' => 'Pregunta frecuente 3',
                'title' => '¿Brindan acompañamiento técnico?',
                'subtitle' => null,
                'body' => 'Sí. Nuestro enfoque incluye asesoría técnica antes, durante y después de la compra.',
                'sort_order' => 3,
                'is_active' => true,
            ],
            [
                'section' => 'location',
                'key' => 'location_main',
                'name' => 'Bloque de ubicación',
                'title' => 'Visítanos',
                'subtitle' => null,
                'body' => null,
                'meta' => [
                    'address_title' => 'Dirección Principal',
                    'address_value' => 'Los Teques, Edo. Miranda. Venezuela',
                    'hours_title' => 'Horarios de Atención',
                    'hours_value' => 'Lunes a Viernes: 8:00 AM - 5:00 PM | Sábados: 8:00 AM - 12:00 PM',
                    'phone_title' => 'Teléfonos',
                    'phone_1' => '+58 (412) 000-0000',
                    'phone_2' => '+58 (414) 000-0000',
                    'map_url' => 'https://www.google.com/maps?q=Los%20Teques%2C%20Miranda%2C%20Venezuela&output=embed',
                ],
                'sort_order' => 1,
                'is_active' => true,
            ],
        ];

        foreach ($items as $item) {
            WebContent::query()->updateOrCreate(
                ['key' => $item['key']],
                $item
            );
        }
    }
}
